eureka:
  client:    
    fetch-registry: false
    register-with-eureka: false   
    #eureka-server-d-n-s-name: DESKTOP-Q50BHSL 
  dashboard:
    enabled: true
spring:
  application:
    name: eureka
server:
  port: 8761
  http2:
    enabled: true