eureka:
  client:
    #eureka-server-d-n-s-name: DESKTOP-Q50BHSL
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: ${PORT:0}
  http2:
    enabled: true
  forward-headers-strategy: framework
spring:
  application:
    name: za1975-gateway
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest  
  cloud:
    gateway:
      routes:
      - id: data-accessor-service
        predicates:        - Path= /accessors/access/**
        - Header= Accept-Language
        uri: lb://ACCESSOR-SERVICE
             
      - id: user-services-register
        predicates:
        - Path= /user/users/register        
        uri: lb://USER-DATA
        
      - id: user-services-login
        predicates:
        - Path= /user/users/login
        uri: lb://USER-DATA
      
      - id: user-services
        predicates:
        - Path= /user/users/**
        - Header= Authorization, Bearer (.*)
        filters:
        - AuthorizationFilter
        uri: lb://USER-DATA
      
      - id: user-service-actuator
        uri: lb://USER-DATA          
        predicates:
        - Path= /user/actuator/** 
management:
  endpoint:
    refresh:
      enabled: true  
  endpoints:
    web:
      exposure:
        include:        
        - bus-refresh
        - bus-env
       
token:
 secrit-key: 7e85t6M60:70
 prefix: Bearer
           