eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone:  http://localhost:8761/eureka
server:
  http2:
    enabled: true
  port: ${PORT:0}  servlet:    context-path: /accessors
spring:
  application:
    name: manage-service      
        
feign:  client:    config:      dataClient:
        error-decoder: com.manage.service.mangement.equity.util.EquityClientErrorDecoder
        request-interceptors:        -  com.manage.service.mangement.equity.client.intrcepator.EquityDataClientRequestInterceptor 
  