eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http:localhost:8017/eurka
server:
  http2:
    enabled: true
  port: ${PORT:0}
spring:
  application:
    name: manage-service
